federation_version: =2.5.4
subgraphs:
  users:
    routing_url: http://127.0.0.1:3065/
    schema:
      subgraph_url: http://127.0.0.1:3065/
  products:
    routing_url: http://127.0.0.1:3075/
    schema:
      subgraph_url: http://127.0.0.1:3075/
  reviews:
    routing_url: http://127.0.0.1:3085/
    schema:
      subgraph_url: http://127.0.0.1:3085/
