[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 3000
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = []
# Paths to ignore.
ignore = []

[[proxy]]
rewrite = "/graphql"
backend = "http://localhost:3040/"
