name: Build Lambda Microservice

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      with-openssl:
        required: false
        type: boolean
      with-protobuf:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update dependencies
        if: ${{ inputs.with-openssl || inputs.with-protobuf }}
        run: sudo apt-get update

      - name: Install openssl (if needed)
        if: ${{ inputs.with-openssl }}
        run: sudo apt-get install -y libssl-dev openssl ca-certificates

      - name: Install protobuf (if needed)
        if: ${{ inputs.with-protobuf }}
        run: sudo apt-get install -y protobuf-compiler

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Zig toolchain (used for cross-compilation)
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.0

      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          platform: linux # Other valid options: 'windows' or 'darwin'.
          arch: x86_64 # Other valid options for linux: 'aarch64'.

      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ inputs.working-directory }}/target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.working-directory }}
          restore-keys: cargo-

      - name: Build release
        working-directory: ${{ inputs.working-directory }}
        run: cargo lambda build --arm64 --release
