name: Check dependencies

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      toolchain:
        required: false
        type: string
        default: stable

jobs:
  unused:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Install cargo-udeps
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: est31/cargo-udeps
          platform: linux
          arch: x86_64

      - name: Find unused dependencies
        run: cargo udeps
        working-directory: ${{ inputs.working-directory }}

  # outdated:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: ${{ inputs.toolchain }}

  #     - name: Install cargo-udeps
  #       uses: jaxxstorm/action-install-gh-release@v1.9.0
  #       with:
  #         repo: kbknapp/cargo-outdated
  #         platform: linux
  #         arch: x86_64

  #     - name: Find outdated dependencies
  #       run: cargo outdated --exit-code 1
  #       working-directory: ${{ inputs.working-directory }}

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Install cargo-udeps
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: rustsec/rustsec
          platform: linux
          arch: x86_64

      - name: Audit Cargo.lock for security vulnerabilities via RustSec Advisory Database
        run: |
          rm -rf ~/.cargo/advisory-db
          cargo audit
        working-directory: ${{ inputs.working-directory }}

  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Install cargo-udeps
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: EmbarkStudios/cargo-deny
          platform: linux
          arch: x86_64

      - name: Ling dependencies and their licenses
        run: cargo deny check --config ../.github/deny.toml --hide-inclusion-graph
        working-directory: ${{ inputs.working-directory }}
