name: "Deployment: Deploy to AWS"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash # Set the default shell to bash.

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        # Add new environments to this list to run bootstrap on them when manually triggered.
        environment:
          - "Integration Test"
          # - "Production Single-tenant"
          # - "Production Multi-tenant"
    uses: ./.github/workflows/wf-deploy.yml
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit

    # steps:
    #   - uses: actions/checkout@v3
    #   - uses: oven-sh/setup-bun@v1

    #   - name: Install dependencies
    #     working-directory: ./deployment
    #     run: bun install

    #   - name: Synthesize the whole stack
    #     working-directory: ./deployment
    #     env:
    #       DOMAIN: ${{ vars.DOMAIN }}
    #       AWS_REGION: ${{ vars.AWS_REGION }}
    #       AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     run: bun run cdk synth --all

    #   - name: Run tests
    #     working-directory: ./deployment
    #     env:
    #       DOMAIN: ${{ vars.DOMAIN }}
    #       AWS_REGION: ${{ vars.AWS_REGION }}
    #       AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    #     run: bun test

    #   - name: Deploy to ${{ matrix.environment }}
    #     working-directory: ./deployment
    #     env:
    #       DOMAIN: ${{ vars.DOMAIN }}
    #       AWS_REGION: ${{ vars.AWS_REGION }}
    #       AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     run: bun run cdk deploy --all --require-approval never
