name: 'Deployment: Deploy to AWS'

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash # Set the default shell to bash.

jobs:
  # Build deployment artifacts
  build-artifacts:
    name: 'Stage 0: Build Artifacts'
    uses: ./.github/workflows/wf-build.yml
    with:
      git-sha: ${{ github.sha }}

  build-images:
    name: 'Stage 0: Build Images'
    strategy:
      matrix:
        environment:
          - 'Integration Test'
          - 'Production Single-tenant'
          - 'Production Multi-tenant'
    uses: ./.github/workflows/wf-build-docker.yml
    with:
      environment: ${{ matrix.environment }}
      project: ms-router
      tag: ${{ github.sha }}
      tag-env-name: SUPERGRAPH_ROUTER_IMAGE_TAG
      push-image: true
    secrets: inherit

  # Stage 1 tests that the deployment is working correctly.
  stage-1:
    name: 'Stage 1: Integration'
    needs: [build-artifacts, build-images]
    uses: ./.github/workflows/wf-deploy.yml
    with:
      environment: 'Integration Test'
      git-sha: ${{ github.sha }}
    secrets: inherit

  # Run tests against the environments from Stage 1.
  stage-1-check:
    name: 'Stage 1: Check Integration'
    needs: [stage-1]
    uses: ./.github/workflows/wf-check.yml
    with:
      environment: 'Integration Test'
    secrets: inherit

  # Stage 2 is our more critical environments, and only proceeds if prior stages succeed.
  stage-2-single:
    name: 'Stage 2: Single-tenant'
    needs: [stage-1-check]
    uses: ./.github/workflows/wf-deploy.yml
    with:
      environment: 'Production Single-tenant'
      git-sha: ${{ github.sha }}
    secrets: inherit

  stage-2-single-check:
    name: 'Stage 2: Check Single-tenant'
    needs: [stage-2-single]
    uses: ./.github/workflows/wf-check.yml
    with:
      environment: 'Production Single-tenant'
    secrets: inherit

  stage-2-multi:
    name: 'Stage 2: Multi-tenant'
    needs: [stage-1-check]
    uses: ./.github/workflows/wf-deploy.yml
    with:
      environment: 'Production Multi-tenant'
      git-sha: ${{ github.sha }}
    secrets: inherit

  stage-2-multi-check:
    name: 'Stage 2: Check Multi-tenant'
    needs: [stage-2-multi]
    uses: ./.github/workflows/wf-check.yml
    with:
      environment: 'Production Multi-tenant'
    secrets: inherit
