name: "CI: Check"

on:
  workflow_dispatch:
  push:
    paths:

defaults:
  run:
    shell: bash # Set the default shell to bash.

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        service:
          - ms-router
          - ms-queue
          - ms-gql-todo
          - ms-gql-media
          - ui-app
    uses: ./.github/workflows/wf-check-dependencies.yml
    with:
      working-directory: ${{ matrix.service }}
