name: 'CI: lib-handler'

on:
  push:
    branches-ignore:
      - main
    paths:
      - '.github/workflows/ci-lib-handler.yml'
      - '.github/workflows/wf-build-crate.yml'
      - 'lib-handler/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

defaults:
  run:
    shell: bash # Set the default shell to bash.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/wf-build-crate.yml
    with:
      project: lib-handler
