name: 'CI: ms-gql-reviews'

on:
  push:
    branches-ignore:
      - main
    paths:
      - '.github/workflows/ci-ms-gql-reviews.yml'
      - '.github/workflows/wf-build-lambda.yml'
      - 'ms-gql-reviews/**'
      - 'lib-handler/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

defaults:
  run:
    shell: bash # Set the default shell to bash.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/wf-build-lambda.yml
    with:
      project: ms-gql-reviews
