name: 'CI: ms-mesh'

on:
  push:
    paths:
      - 'ms-mesh/**'
      - '.github/workflows/ci-ms-mesh.yml'
      - '.github/workflows/wf-build-ms-mesh.yml'

defaults:
  run:
    shell: bash # Set the default shell to bash.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/wf-build-ms-mesh.yml
