name: 'CI: ms-gateway'

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'ms-gateway/**'
      - '.github/workflows/ci-ms-gateway.yml'
      - '.github/workflows/wf-build-ms-gateway.yml'

defaults:
  run:
    shell: bash # Set the default shell to bash.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/wf-build-ms-gateway.yml
