name: 'CI: ui-internal'

on:
  push:
    branches-ignore:
      - main
    paths:
      - '.github/workflows/ci-ui-internal.yml'
      - '.github/workflows/wf-build-ui-internal.yml'
      - 'ui-internal/**'

defaults:
  run:
    shell: bash # Set the default shell to bash.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/wf-build-ui-internal.yml

  end-to-end:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: 'true'
      RUSTC_WRAPPER: 'sccache'
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: extractions/setup-just@v1
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-11-29
          targets: wasm32-unknown-unknown

      - name: Install trunk
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: thedodd/trunk
          platform: linux # Other valid options: 'windows' or 'darwin'.
          arch: x86_64

      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ui-internal/target
          key: cargo-debug-${{ hashFiles('ui-internal/Cargo.lock') }}-ui-internal
          restore-keys: |
            cargo-debug-${{ hashFiles('ui-internal/Cargo.lock') }}-ui-internal
            cargo-debug-
      - uses: mozilla-actions/sccache-action@v0.0.3
        name: 'Setup sccache'

      - name: Install dependencies and setup Playwright
        working-directory: ./ui-internal/end2end
        run: |
          bun install
          bun run setup

      - name: Build debug build
        run: just build ui-internal debug

      - name: Run end-to-end tests
        run: just e2e ui-internal
