name: CI

on:
  workflow_dispatch:
  push:
    paths:

defaults:
  run:
    shell: bash # Set the default shell to bash.

jobs:
  services:
    strategy:
      fail-fast: false
      matrix:
        service:
          - ms-router
          - ms-queue
          - ms-gql-todo
          - ms-gql-media
    uses: ./.github/workflows/wf-build-lambda.yml
    with:
      working-directory: ${{ matrix.service }}
    # secrets: inherit

  apps:
    strategy:
      fail-fast: false
      matrix:
        service:
          - ui-app
    uses: ./.github/workflows/wf-build-wasm.yml
    with:
      working-directory: ${{ matrix.service }}
