name: CI

on:
  workflow_dispatch:
  push:
    paths:

defaults:
  run:
    shell: bash # Set the default shell to bash.

jobs:
  services:
    strategy:
      fail-fast: false
      matrix:
        service:
          - ms-queue
          - ms-gql-todo
          - ms-gql-media
    uses: ./.github/workflows/wf-build-lambda.yml
    with:
      working-directory: ${{ matrix.service }}
    # secrets: inherit

  ui-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown

      - name: Install trunk
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: thedodd/trunk
          platform: linux # Other valid options: 'windows' or 'darwin'.
          arch: x86_64

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build release
        working-directory: ui-app
        run: trunk build --release
