name: 'Vercel: E2E'

on:
  deployment_status:

jobs:
  ui-app:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Production – ui-app'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies and setup Playwright
        run: just setup deployment

      - name: End-to-end tests
        working-directory: ./deployment
        env:
          UI_APP_E2E_URL: ${{ github.event.deployment_status.environment_url }}
        run: |
          echo "Running tests against '${UI_APP_E2E_URL}'."
          just e2e deployment ui-app
