name: "Build: ms-gql"

on:
  workflow_call:
    inputs:
      project:
          type: string
          required: true
      release:
        type: boolean
        default: false
      upload-artifact:
        type: boolean
        default: false

jobs:
  ui-internal:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11.0
      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          platform: linux
          arch: aarch64 # Other valid options for linux: 'x86_64'

      - uses: mozilla-actions/sccache-action@v0.0.3
        name: "Setup sccache"

      - name: Build release build
        if: ${{ inputs.release }}
        run: just build ${{ inputs.project }}

      - name: Build debug build
        if: ${{ !inputs.release }}
        run: just build ${{ inputs.project }} true

      - uses: actions/upload-artifact@v3
        if: ${{ inputs.upload-artifact }}
        with:
          name: ${{ inputs.project }}
          path: target/lambda/${{ inputs.project }}
          if-no-files-found: error
          retention-days: 1
