name: 'Build: ms-router'

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      release:
        type: boolean
        default: false
      push-image:
        type: boolean
        default: false

jobs:
  build:
    name: ${{ inputs.project }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
      - uses: oven-sh/setup-bun@v1
      - uses: extractions/setup-just@v1

      - name: Install dependencies
        run: just setup ms-router

      - name: Build project
        run: just build ms-router

      - uses: actions/upload-artifact@v3
        if: ${{ inputs.push-image }}
        with:
          name: ms-router
          path: ms-router/dist
          if-no-files-found: error
          retention-days: 1
