name: 'Build: ui-internal'

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
      upload-artifact:
        type: boolean
        default: false

jobs:
  ui-internal:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: 'true'
      RUSTC_WRAPPER: 'sccache'
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: extractions/setup-just@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-10-11
          target: wasm32-unknown-unknown
          cache: false

      - name: Install trunk
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: thedodd/trunk
          platform: linux # Other valid options: 'windows' or 'darwin'.
          arch: x86_64

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ui-internal
      - uses: mozilla-actions/sccache-action@v0.0.3
        name: 'Setup sccache'

      - name: Build release build
        if: ${{ inputs.release }}
        run: just build ui-internal

      - name: Build debug build
        if: ${{ !inputs.release }}
        run: just build ui-internal debug

      - uses: actions/upload-artifact@v3
        if: ${{ inputs.upload-artifact }}
        with:
          name: ui-internal
          path: ui-internal/dist
          if-no-files-found: error
          retention-days: 1
