name: "Build: ui-internal"

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
      upload-artifact:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: extractions/setup-just@v1
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-10-11
          targets: wasm32-unknown-unknown

      - name: Install trunk
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: thedodd/trunk
          platform: linux # Other valid options: 'windows' or 'darwin'.
          arch: x86_64

      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ui-internal/target
          key: cargo-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('ui-internal/Cargo.lock') }}-ui-internal
          restore-keys: cargo-

      - name: Build release build
        if: ${{ github.event.inputs.release == 'true' }}
        run: just build ui-internal

      - name: Build debug build
        if: ${{ github.event.inputs.release != 'true' }}
        run: just build ui-internal true

      - uses: actions/upload-artifact@v3
        if: ${{ github.event.inputs.upload-artifact == 'true' }}
        with:
          name: ui-internal
          path: ui-internal/dist
