name: 'Build Artifacts'

on:
  workflow_call:
    inputs:
      git-sha:
        required: true
        type: string

jobs:
  ui-app:
    uses: ./.github/workflows/wf-build-ui-app.yml
    with:
      release: true
      upload-artifact: true

  ui-internal:
    uses: ./.github/workflows/wf-build-ui-internal.yml
    with:
      release: true
      upload-artifact: true

  ms-gql-users:
    uses: ./.github/workflows/wf-build-lambda.yml
    with:
      project: ms-gql-users
      release: true
      upload-artifact: true

  ms-gql-products:
    uses: ./.github/workflows/wf-build-lambda.yml
    with:
      project: ms-gql-products
      release: true
      upload-artifact: true

  ms-gql-reviews:
    uses: ./.github/workflows/wf-build-lambda.yml
    with:
      project: ms-gql-reviews
      release: true
      upload-artifact: true

  ms-gateway:
    uses: ./.github/workflows/wf-build-ms-gateway.yml
    with:
      release: true
      upload-artifact: true

  ms-mesh:
    uses: ./.github/workflows/wf-build-ms-mesh.yml
    with:
      release: true
      upload-artifact: true

  ms-router:
    uses: ./.github/workflows/wf-build-docker.yml
    with:
      project: ms-router
      tag: ${{ inputs.git-sha }}
      tag-env-name: SUPERGRAPH_ROUTER_IMAGE_TAG
      push-image: true
