name: 'Build: Docker'

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      tag:
        type: string
        required: true
      tag-env-name:
        type: string
        description: The name of the environment variable that defines the tag for the image
        required: true
      push-image:
        type: boolean
        default: false

jobs:
  build:
    name: ${{ inputs.project }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image to ECR
        if: ${{ inputs.push-image }}
        run: |
          export ${{ inputs.tag-env-name }}=${{ inputs.tag }}
          just build ${{ inputs.project }}
