name: 'Build: crate'

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true

jobs:
  build:
    name: ${{ inputs.project }}
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: 'true'
      RUSTC_WRAPPER: 'sccache'
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - uses: mozilla-actions/sccache-action@v0.0.3
        name: 'Setup sccache'

      - name: Build release build
        working-directory: ${{ inputs.project }}
        run: cargo build
