name: 'Build: Docker'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project:
        type: string
        required: true
      tag:
        type: string
        required: true
      tag-env-name:
        type: string
        description: The name of the environment variable that defines the tag for the image
        required: true
      push-image:
        type: boolean
        default: false

jobs:
  build:
    name: ${{ inputs.project }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ vars.DOMAIN }}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Prepare the project to be built
        run: |
          export ${{ inputs.tag-env-name }}=${{ inputs.tag }}
          just docker-prepare ${{ inputs.project }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.project }}
          tags: ${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push the image to ECR
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export ${{ inputs.tag-env-name }}=${{ inputs.tag }}
          just docker-push ${{ inputs.project }}
