name: Check

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

defaults:
  run:
    shell: bash # Set the default shell to bash.

jobs:
  check:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ vars.DOMAIN }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: extractions/setup-just@v1

      - name: Install dependencies and setup Playwright
        run: just setup deployment

      - name: End-to-end tests
        working-directory: ./deployment
        env:
          DOMAIN: ${{ vars.DOMAIN }}
        run: just e2e deployment
